name: Deadnix
on: [push, pull_request]
env:
  committer_name: Invio bot
  committer_email: bot@inversiones.io

jobs:
  deadnix-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v22

      - uses: cachix/cachix-action@v12
        with:
          name: deadnix

      - name: Code clean up + pull request
        uses: luisnquin/deadnix-action@main
        with:
          author: ${{env.committer_name}} <${{env.committer_email}}>
          committer: ${{env.committer_name}} <${{env.committer_email}}>
          commit_message: "deadnix: removed dead code"
